import {
  DashboardMetrics,
  Transaction,
  CuratedScenarioSummary,
  CuratedScenarioTrace,
} from './api';
import evaluationReportJson from './evaluation_report.json';
import latestBenchmarkJson from './latest_benchmark.json';

export const MOCK_DASHBOARD_METRICS: DashboardMetrics = {
  total_failed_volume: 1245800,
  total_failed_count: 142,
  total_revenue_recovered: 718400,
  total_recovered_count: 98,
  recovery_rate: 0.742,
  active_escalations_count: 4,
  ai_uplift_percentage: 50.1,
  revenue_at_risk: 1245800,
  recoverable_revenue: 845200,
  revenue_recovered: 718400,
  failed_payments_count: 114,
  abandoned_checkouts_count: 28,
  active_recoveries_count: 12,
  escalations_count: 4,
  by_failure_category: {
    TEMPORARY: 42,
    PAYMENT_METHOD: 36,
    BANK: 28,
    ABANDONMENT: 20,
    RISK: 12,
    DUPLICATE: 4,
  },
  by_recovery_action: {
    RETRY_PAYMENT: 45,
    SWITCH_PAYMENT_METHOD: 32,
    SCHEDULE_RETRY: 24,
    SEND_RECOVERY_MESSAGE: 18,
    ESCALATE: 12,
    STOP: 11,
  },
  baseline_vs_ai: {
    baseline_recovery_rate: 0.241,
    ai_recovery_rate: 0.742,
    baseline_volume: 300237,
    ai_volume: 718400,
    uplift_pct: 50.1,
  },
  recovery_probability_distribution: [
    { range: '0-20%', count: 14 },
    { range: '20-40%', count: 22 },
    { range: '40-60%', count: 35 },
    { range: '60-80%', count: 48 },
    { range: '80-100%', count: 23 },
  ],
  revenue_over_time: [
    { timestamp: '10:00', ai_recovered: 120000, baseline_recovered: 45000, at_risk: 210000 },
    { timestamp: '11:00', ai_recovered: 250000, baseline_recovered: 95000, at_risk: 390000 },
    { timestamp: '12:00', ai_recovered: 410000, baseline_recovered: 160000, at_risk: 620000 },
    { timestamp: '13:00', ai_recovered: 580000, baseline_recovered: 220000, at_risk: 890000 },
    { timestamp: '14:00', ai_recovered: 718400, baseline_recovered: 300237, at_risk: 1245800 },
  ],
};

export const MOCK_CURATED_SCENARIOS: CuratedScenarioSummary[] = [
  {
    scenario_id: 'scenario_gateway_timeout',
    index: 1,
    title: 'Gateway Timeout → Successful Retry',
    description: 'Transient network timeout at bank switch on UPI rail. System classifies as temporary failure, ML confirms high recovery potential, policy permits retry, agent executes immediate retry, simulator captures payment.',
    category: 'TEMPORARY',
    badge_color: 'emerald',
    amount: 3499.0,
    currency: 'INR',
    payment_method: 'UPI',
    failure_code: 'GATEWAY_TIMEOUT',
    risk_score: 0.04,
    customer_name: 'Rajesh Kumar',
    merchant_name: 'Zomato Online',
    expected_action: 'RETRY_PAYMENT',
    is_executed: true,
    recovered: true,
    revenue_recovered: 3499.0,
    selected_action: 'RETRY_PAYMENT',
    policy_outcome: 'PERMITTED',
    last_run_timestamp: new Date().toISOString(),
  },
  {
    scenario_id: 'scenario_insufficient_funds',
    index: 2,
    title: 'Insufficient Funds → Retry Denied / Poor Candidate',
    description: 'Customer account has insufficient funds. Policy engine enforces 300-second cooling period and blocks immediate retry to prevent futile retry fees.',
    category: 'BANK',
    badge_color: 'amber',
    amount: 12500.0,
    currency: 'INR',
    payment_method: 'NETBANKING',
    failure_code: 'INSUFFICIENT_FUNDS',
    risk_score: 0.12,
    customer_name: 'Priya Sharma',
    merchant_name: 'Flipkart India',
    expected_action: 'SCHEDULE_RETRY',
    is_executed: true,
    recovered: false,
    revenue_recovered: 0.0,
    selected_action: 'SCHEDULE_RETRY',
    policy_outcome: 'BLOCKED',
    last_run_timestamp: new Date().toISOString(),
  },
  {
    scenario_id: 'scenario_expired_card',
    index: 3,
    title: 'Expired Card → Switch Payment Method',
    description: 'Recurring subscription renewal failed because card is past expiry date. Policy rule POL-008 blocks card retry; agent switches to verified UPI VPA.',
    category: 'PAYMENT_METHOD',
    badge_color: 'blue',
    amount: 4999.0,
    currency: 'INR',
    payment_method: 'CARD',
    failure_code: 'CARD_EXPIRED',
    risk_score: 0.08,
    customer_name: 'Amit Patel',
    merchant_name: 'Hotstar VIP',
    expected_action: 'SWITCH_PAYMENT_METHOD',
    is_executed: true,
    recovered: true,
    revenue_recovered: 4999.0,
    selected_action: 'SWITCH_PAYMENT_METHOD',
    policy_outcome: 'PERMITTED',
    last_run_timestamp: new Date().toISOString(),
  },
  {
    scenario_id: 'scenario_checkout_abandonment',
    index: 4,
    title: 'Checkout Abandonment → Recovery Message',
    description: 'High-intent shopper abandoned luxury electronics cart at payment method step. Policy POL-009 verifies DND status; agent dispatches 1-click payment link.',
    category: 'ABANDONMENT',
    badge_color: 'purple',
    amount: 8999.0,
    currency: 'INR',
    payment_method: 'UPI',
    failure_code: 'CUSTOMER_ABANDONED',
    risk_score: 0.06,
    customer_name: 'Sneha Reddy',
    merchant_name: 'Boat Audio Direct',
    expected_action: 'SEND_RECOVERY_MESSAGE',
    is_executed: true,
    recovered: true,
    revenue_recovered: 8999.0,
    selected_action: 'SEND_RECOVERY_MESSAGE',
    policy_outcome: 'PERMITTED',
    last_run_timestamp: new Date().toISOString(),
  },
  {
    scenario_id: 'scenario_high_risk_transaction',
    index: 5,
    title: 'High-Risk Transaction → Stop / Escalate',
    description: 'High-value transaction flagged with risk score 0.94. Policy rule POL-003 strictly blocks automated actions, escalating to risk operations.',
    category: 'RISK',
    badge_color: 'red',
    amount: 85000.0,
    currency: 'INR',
    payment_method: 'CARD',
    failure_code: 'HIGH_RISK',
    risk_score: 0.94,
    customer_name: 'Vikram Malhotra',
    merchant_name: 'Tanishq Jewellers',
    expected_action: 'ESCALATE',
    is_executed: true,
    recovered: false,
    revenue_recovered: 0.0,
    selected_action: 'ESCALATE',
    policy_outcome: 'BLOCKED',
    last_run_timestamp: new Date().toISOString(),
  },
  {
    scenario_id: 'scenario_pending_payment',
    index: 6,
    title: 'Pending Payment → Wait (Prevent Double Debit)',
    description: 'Bank switch returned asynchronous PENDING status. Policy POL-007 intercepts transaction and prohibits retrying to prevent customer double-debit.',
    category: 'TEMPORARY',
    badge_color: 'amber',
    amount: 15400.0,
    currency: 'INR',
    payment_method: 'NETBANKING',
    failure_code: 'BANK_PROCESSING_PENDING',
    risk_score: 0.05,
    customer_name: 'Ananya Deshmukh',
    merchant_name: 'MakeMyTrip Flights',
    expected_action: 'WAIT',
    is_executed: true,
    recovered: false,
    revenue_recovered: 0.0,
    selected_action: 'WAIT',
    policy_outcome: 'BLOCKED',
    last_run_timestamp: new Date().toISOString(),
  },
  {
    scenario_id: 'scenario_duplicate_payment',
    index: 7,
    title: 'Duplicate Payment → Stop (Idempotency Lock)',
    description: 'Identical idempotency key received within 15 seconds. Policy rule POL-002 enforces idempotency lock, permanently halting redundant attempt.',
    category: 'DUPLICATE',
    badge_color: 'slate',
    amount: 1850.0,
    currency: 'INR',
    payment_method: 'UPI',
    failure_code: 'DUPLICATE_PAYMENT',
    risk_score: 0.02,
    customer_name: 'Rohit Verma',
    merchant_name: 'Swiggy Instamart',
    expected_action: 'STOP',
    is_executed: true,
    recovered: false,
    revenue_recovered: 0.0,
    selected_action: 'STOP',
    policy_outcome: 'BLOCKED',
    last_run_timestamp: new Date().toISOString(),
  },
  {
    scenario_id: 'scenario_order_creation_failure',
    index: 8,
    title: 'Order Creation Failure → Reconciliation / Escalation',
    description: 'Merchant OMS failed to provision order after payment captured. Policy POL-001 detects successful capture; agent routes to reconciliation.',
    category: 'MERCHANT',
    badge_color: 'cyan',
    amount: 6200.0,
    currency: 'INR',
    payment_method: 'CARD',
    failure_code: 'ORDER_CREATION_FAILED',
    risk_score: 0.03,
    customer_name: 'Deepika Sen',
    merchant_name: 'Myntra Fashion',
    expected_action: 'ESCALATE',
    is_executed: true,
    recovered: true,
    revenue_recovered: 6200.0,
    selected_action: 'ESCALATE',
    policy_outcome: 'PERMITTED',
    last_run_timestamp: new Date().toISOString(),
  },
];

export function getMockCuratedScenarioTrace(scenarioId: string): CuratedScenarioTrace {
  const summary = MOCK_CURATED_SCENARIOS.find((s) => s.scenario_id === scenarioId) || MOCK_CURATED_SCENARIOS[0];

  return {
    scenario_id: summary.scenario_id,
    index: summary.index,
    title: summary.title,
    category: summary.category,
    executed_at: new Date().toISOString(),
    input: {
      scenario_id: summary.scenario_id,
      title: summary.title,
      description: summary.description,
      transaction_id: `txn_${summary.scenario_id.replace('scenario_', '')}_001`,
      amount: summary.amount,
      currency: summary.currency,
      payment_method: summary.payment_method,
      gateway: 'RAZORPAY',
      failure_code: summary.failure_code,
      risk_score: summary.risk_score,
      initial_status: 'FAILED',
      attempt_number: 1,
      customer: {
        customer_id: 'cust_sample_user',
        name: summary.customer_name,
        preferred_payment_method: summary.payment_method,
        risk_score: summary.risk_score,
        success_rate: 0.92,
        total_transactions: 18,
      },
      merchant: {
        merchant_id: 'merch_sample_merchant',
        name: summary.merchant_name,
        business_type: 'Ecommerce & Subscription',
      },
      timestamp: new Date().toISOString(),
      idempotency_key: `idem_${summary.scenario_id}_seed_2026`,
      metadata: {},
    },
    root_cause: {
      failure_code: summary.failure_code,
      category: summary.category,
      diagnosed_cause: summary.description,
      confidence: 0.96,
      is_retryable: summary.category === 'TEMPORARY',
      recommended_action: summary.expected_action,
      explanation: summary.description,
      raw_attributes: {
        temporary: summary.category === 'TEMPORARY',
      },
    },
    ml_prediction: {
      model_version: 'XGBoost Tabular Classifier v2.1.0',
      recovery_probability: summary.recovered ? 0.88 : 0.12,
      expected_value: summary.recovered ? Math.round(summary.amount * 0.88) : 0,
      confidence_band: {
        lower: summary.recovered ? 0.82 : 0.08,
        upper: summary.recovered ? 0.94 : 0.18,
      },
      feature_contributions: {
        customer_success_rate: 0.35,
        payment_method_health: 0.28,
        failure_code_recoverability: 0.22,
        risk_score_penalty: -0.05,
      },
      inference_latency_ms: 3.8,
    },
    candidate_actions: [
      {
        action: summary.expected_action,
        probability: summary.recovered ? 0.88 : 0.12,
        expected_recovery_value: summary.recovered ? Math.round(summary.amount * 0.88) : 0,
        rank: 1,
        permitted_by_policy: summary.policy_outcome === 'PERMITTED',
        policy_reason: summary.policy_outcome === 'PERMITTED' ? 'Permitted by policy' : 'Blocked by policy guardrail',
      },
      {
        action: 'RETRY_PAYMENT',
        probability: 0.42,
        expected_recovery_value: Math.round(summary.amount * 0.42),
        rank: 2,
        permitted_by_policy: summary.expected_action === 'RETRY_PAYMENT',
        policy_reason: summary.expected_action === 'RETRY_PAYMENT' ? 'Permitted' : 'Sub-optimal candidate',
      },
    ],
    policy: {
      decision: summary.policy_outcome,
      outcome: summary.policy_outcome,
      rule_id: 'POL-004',
      reason: `Enforced by policy: ${summary.description}`,
      severity: summary.category === 'RISK' ? 'CRITICAL' : 'HIGH',
      recommended_action: summary.expected_action,
      rules_evaluated: [
        { rule_id: 'POL-001', title: 'Successful Payment Immutability', status: 'PASSED', severity: 'CRITICAL' },
        { rule_id: 'POL-002', title: 'Duplicate Payment & Idempotency Lock', status: 'PASSED', severity: 'CRITICAL' },
        { rule_id: 'POL-003', title: 'Fraud Risk Threshold Check', status: summary.category === 'RISK' ? 'BLOCKED' : 'PASSED', severity: 'CRITICAL' },
        { rule_id: 'POL-004', title: 'Maximum Retry Ceiling Check', status: 'PASSED', severity: 'HIGH' },
      ],
      enforced_constraints: {
        max_retries_allowed: 3,
        current_attempt: 1,
        fraud_threshold: 0.85,
        cooling_period_seconds: 300,
      },
    },
    agent_decision: {
      selected_action: summary.selected_action,
      reasoning: `Agent selected ${summary.selected_action} with estimated recovery probability of ${summary.recovered ? '88%' : '12%'}.`,
      execution_parameters: {
        target_payment_method: summary.payment_method,
        retry_delay_seconds: 0,
        enforce_idempotency: true,
      },
      fallback_mode: false,
      execution_pipeline: [
        'Input Validation',
        'Taxonomy Classification',
        'XGBoost Inference',
        'Policy Enforcement Gate',
        'Simulator Execution',
      ],
      agent_latency_ms: 4.2,
    },
    simulator_result: {
      execution_status: summary.recovered ? 'SUCCESS' : 'FAILED',
      from_state: 'FAILED',
      to_state: summary.recovered ? 'SUCCESS' : 'BLOCKED',
      latency_ms: 18.5,
      gateway_response: {
        response_code: summary.recovered ? '200_OK' : '400_BLOCKED',
        rrn: 'RRN-SIM-829104819',
        simulated_rail: summary.payment_method,
      },
      terminal: true,
      simulated: true,
      environment: 'Sandbox Payment State Machine',
    },
    revenue_recovered: {
      amount: summary.revenue_recovered,
      currency: summary.currency,
      recovered: summary.recovered,
      status: summary.recovered ? 'SUCCESS' : 'BLOCKED',
      economic_impact_summary: summary.recovered
        ? `Successfully recovered ₹${summary.revenue_recovered.toLocaleString('en-IN')} without user friction.`
        : 'Protected merchant margin and eliminated futile retry fees.',
      revenue_at_risk: summary.amount,
      recovery_rate_contribution: summary.recovered ? 1.0 : 0.0,
    },
    audit_trail: {
      total_events: 4,
      verified_integrity: true,
      latest_hash: '9f82d1c4e7b8a532d601f4c7e8a9b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9',
      events: [
        {
          index: 1,
          event_id: 'evt_001',
          timestamp: new Date().toISOString(),
          actor: 'System / Ingestion',
          event_type: 'PAYMENT_FAILURE_INGESTED',
          hash: 'a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2',
          previous_hash: null,
        },
        {
          index: 2,
          event_id: 'evt_002',
          timestamp: new Date().toISOString(),
          actor: 'Failure Classifier',
          event_type: 'ROOT_CAUSE_DIAGNOSED',
          hash: 'b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3',
          previous_hash: 'a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2',
        },
        {
          index: 3,
          event_id: 'evt_003',
          timestamp: new Date().toISOString(),
          actor: 'Policy Engine',
          event_type: 'POLICY_EVALUATED_AND_PASSED',
          hash: 'c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4',
          previous_hash: 'b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3',
        },
        {
          index: 4,
          event_id: 'evt_004',
          timestamp: new Date().toISOString(),
          actor: 'Recovery Agent',
          event_type: 'ACTION_EXECUTED',
          hash: '9f82d1c4e7b8a532d601f4c7e8a9b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9',
          previous_hash: 'c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4',
        },
      ],
    },
  };
}

export const MOCK_TRANSACTIONS: Transaction[] = MOCK_CURATED_SCENARIOS.map((s) => ({
  transaction_id: `txn_${s.scenario_id.replace('scenario_', '')}_001`,
  customer_id: 'cust_demo_user',
  merchant_id: 'merch_demo_merchant',
  amount: s.amount,
  currency: s.currency,
  payment_method: s.payment_method,
  gateway: 'RAZORPAY',
  status: s.recovered ? 'SUCCESS' : 'FAILED',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  ai: {
    root_cause: s.category,
    recovery_probability: s.recovered ? 0.88 : 0.12,
    recommended_action: s.selected_action,
    policy_decision: s.policy_outcome,
    policy_rule_id: 'POL-004',
    expected_recovery_value: s.recovered ? Math.round(s.amount * 0.88) : 0,
    reasoning: s.description,
  },
}));

export const MOCK_BASELINE_COMPARISON = {
  cohort_metadata: {
    total_transactions: 1000,
    total_attempted_gmv: 5400000,
    dataset_version: 'synthetic_benchmark_v2',
  },
  strategies: [
    {
      strategy_id: 'strat_none',
      name: '1. No Recovery (Passive Control)',
      description: 'Passive control with zero retry or recovery attempts.',
      recovery_rate: 0.0,
      recovered_gmv: 0.0,
      recovered_count: 0,
      fee_cost: 0.0,
      net_value: 0.0,
      policy_violations: 0,
    },
    {
      strategy_id: 'strat_fixed',
      name: '2. Fixed Retry Rule (Industry Standard)',
      description: 'Blind 1-time retry on every failed payment without context.',
      recovery_rate: 0.241,
      recovered_gmv: 1301400.0,
      recovered_count: 241,
      fee_cost: 48200.0,
      net_value: 1253200.0,
      policy_violations: 14,
    },
    {
      strategy_id: 'strat_ml_only',
      name: '3. ML-Only Prediction (Ungated)',
      description: 'Predicts recovery probability and retries if P > 0.5 without guardrails.',
      recovery_rate: 0.584,
      recovered_gmv: 3153600.0,
      recovered_count: 584,
      fee_cost: 21400.0,
      net_value: 3132200.0,
      policy_violations: 6,
    },
    {
      strategy_id: 'strat_decision_engine',
      name: '4. ML + Decision Engine (Value-Optimized)',
      description: 'Ranks 7 candidate actions using Expected Recovery Value formula.',
      recovery_rate: 0.682,
      recovered_gmv: 3682800.0,
      recovered_count: 682,
      fee_cost: 14800.0,
      net_value: 3668000.0,
      policy_violations: 2,
    },
    {
      strategy_id: 'strat_autonomous_agent',
      name: '5. Autonomous ML Agent (Advisory Reasoning)',
      description: 'State graph agent with contextual reasoning and adaptive action tuning.',
      recovery_rate: 0.71,
      recovered_gmv: 3834000.0,
      recovered_count: 710,
      fee_cost: 12100.0,
      net_value: 3821900.0,
      policy_violations: 1,
    },
    {
      strategy_id: 'strat_razorrecover_full',
      name: '6. RazorRecover AI (Full System)',
      description: 'Full stack: ML + Decision Engine + Hard Policy Guardrails + Simulator.',
      recovery_rate: 0.742,
      recovered_gmv: 4006800.0,
      recovered_count: 742,
      fee_cost: 9400.0,
      net_value: 3997400.0,
      policy_violations: 0,
    },
  ],
};

export const MOCK_MODEL_PERFORMANCE_REPORT = evaluationReportJson as any;
export const MOCK_LATEST_BENCHMARK = latestBenchmarkJson as any;

export const MOCK_SUBSCRIPTION_METRICS = {
  total_subscriptions: 1450,
  active_subscriptions: 1210,
  payment_failed_subscriptions: 84,
  retry_scheduled_subscriptions: 42,
  recovered_subscriptions: 96,
  cancelled_subscriptions: 18,
  mrr_at_risk: 420000,
  mrr_recovered: 285000,
};

export const MOCK_SUBSCRIPTIONS = [
  {
    subscription_id: 'sub_enterprise_001',
    customer_id: 'cust_acme_corp',
    plan_name: 'Enterprise Scale Tier',
    mrr: 45000,
    currency: 'INR',
    state: 'PAYMENT_FAILED',
    retry_count: 1,
    max_retries: 4,
    next_retry_at: new Date(Date.now() + 3600000).toISOString(),
    last_failure_code: 'INSUFFICIENT_FUNDS',
    payment_method: 'CARD',
    gateway: 'RAZORPAY',
    risk_score: 0.08,
    created_at: new Date(Date.now() - 86400000 * 45).toISOString(),
    updated_at: new Date().toISOString(),
    history: [
      { timestamp: new Date(Date.now() - 86400000).toISOString(), action: 'RETRY_PAYMENT', status: 'FAILED', failure_code: 'INSUFFICIENT_FUNDS' },
    ],
  },
  {
    subscription_id: 'sub_pro_002',
    customer_id: 'cust_stellar_ai',
    plan_name: 'Pro Developer Plan',
    mrr: 12500,
    currency: 'INR',
    state: 'RETRY_SCHEDULED',
    retry_count: 1,
    max_retries: 3,
    next_retry_at: new Date(Date.now() + 7200000).toISOString(),
    last_failure_code: 'GATEWAY_TIMEOUT',
    payment_method: 'UPI',
    gateway: 'RAZORPAY',
    risk_score: 0.04,
    created_at: new Date(Date.now() - 86400000 * 20).toISOString(),
    updated_at: new Date().toISOString(),
    history: [
      { timestamp: new Date(Date.now() - 7200000).toISOString(), action: 'SCHEDULE_RETRY', status: 'SCHEDULED' },
    ],
  },
  {
    subscription_id: 'sub_growth_003',
    customer_id: 'cust_hyper_retail',
    plan_name: 'Growth eCommerce Monthly',
    mrr: 28000,
    currency: 'INR',
    state: 'RECOVERED',
    retry_count: 2,
    max_retries: 4,
    next_retry_at: null,
    last_failure_code: 'CARD_DECLINED',
    payment_method: 'UPI',
    gateway: 'RAZORPAY',
    risk_score: 0.05,
    created_at: new Date(Date.now() - 86400000 * 60).toISOString(),
    updated_at: new Date().toISOString(),
    history: [
      { timestamp: new Date(Date.now() - 86400000 * 2).toISOString(), action: 'SWITCH_PAYMENT_METHOD', status: 'SUCCESS' },
    ],
  },
  {
    subscription_id: 'sub_starter_004',
    customer_id: 'cust_cloud_labs',
    plan_name: 'Starter Cloud Pod',
    mrr: 4999,
    currency: 'INR',
    state: 'ACTIVE',
    retry_count: 0,
    max_retries: 3,
    next_retry_at: null,
    last_failure_code: null,
    payment_method: 'CARD',
    gateway: 'RAZORPAY',
    risk_score: 0.02,
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    updated_at: new Date().toISOString(),
    history: [],
  },
];

export const MOCK_POLICIES = [
  { policy_id: 'POL-001', name: 'NO_DOUBLE_CHARGE', category: 'FINANCIAL_INTEGRITY', risk_level: 'CRITICAL', description: 'Blocks any retry if terminal capture or pre-auth already verified.' },
  { policy_id: 'POL-002', name: 'MAX_RETRY_LIMIT', category: 'FREQUENCY_CONTROL', risk_level: 'HIGH', description: 'Enforces maximum of 3 recovery attempts per unique transaction ID.' },
  { policy_id: 'POL-003', name: 'HIGH_RISK_BLOCK', category: 'FRAUD_PREVENTION', risk_level: 'CRITICAL', description: 'Blocks automated recovery on transactions with fraud risk score > 0.80.' },
  { policy_id: 'POL-004', name: 'CARD_EXPIRY_GATEWAY', category: 'TECHNICAL_VIABILITY', risk_level: 'MEDIUM', description: 'Redirects expired cards to SWITCH_PAYMENT_METHOD; blocks blind retries.' },
  { policy_id: 'POL-005', name: 'GATEWAY_BACKOFF', category: 'RESILIENCE', risk_level: 'HIGH', description: 'Enforces minimum 300s backoff window on 504 GATEWAY_TIMEOUT errors.' },
  { policy_id: 'POL-006', name: 'INSUFFICIENT_FUNDS_SALARY_CYCLE', category: 'TIMING_INTELLIGENCE', risk_level: 'LOW', description: 'Defers recovery of low-balance debit cards to standard paydays.' },
  { policy_id: 'POL-007', name: 'AUTHENTICATION_USER_PROMPT', category: 'USER_EXPERIENCE', risk_level: 'MEDIUM', description: 'Dispatches interactive UPI push / WhatsApp intent on OTP failures.' },
  { policy_id: 'POL-008', name: 'COOLDOWN_DEDUPLICATION', category: 'DUPLICATE_PROTECTION', risk_level: 'CRITICAL', description: 'Disallows duplicate recovery attempts submitted within 60 seconds.' },
  { policy_id: 'POL-009', name: 'SUBSCRIPTION_GRACE_PERIOD', category: 'RETENTION_SAFETY', risk_level: 'HIGH', description: 'Preserves active entitlement status across 7-day dunning window.' },
  { policy_id: 'POL-010', name: 'COMPLIANCE_CONSENT_CHECK', category: 'REGULATORY', risk_level: 'CRITICAL', description: 'Verifies customer consent token before initiating secondary card charges.' },
  { policy_id: 'POL-011', name: 'VIP_AUTO_ESCALATION', category: 'MERCHANT_EXPERIENCE', risk_level: 'HIGH', description: 'Escalates failures on enterprise merchant transactions > ₹1,00,000.' },
  { policy_id: 'POL-012', name: 'SIMULATOR_NO_REAL_MONEY', category: 'SYSTEM_SAFETY', risk_level: 'CRITICAL', description: 'Guarantees all test payment executions route through sandbox mock rail.' },
];

export const MOCK_SIMULATION_RUN = {
  run_id: 'sim_run_20260905_001',
  seed: 42,
  transaction_count: 20,
  recovered_count: 15,
  recovered_revenue: 84250.0,
  recovery_rate: 0.75,
  status: 'COMPLETED',
  created_at: new Date().toISOString(),
  scenario: 'mixed_failures',
  total_transactions: 20,
  failed_transactions: 20,
  recoverable_opportunities: 18,
  revenue_at_risk: 112330.0,
  baseline_metrics: {
    total_transactions: 20,
    recovered_count: 5,
    recovered_revenue: 28000.0,
    recovery_rate: 0.25,
    fee_cost: 1600.0,
    net_value: 26400.0,
    unnecessary_retries: 12,
    policy_violations: 4,
    escalations: 0,
    average_recovery_time_ms: 1250,
  },
  ai_metrics: {
    total_transactions: 20,
    recovered_count: 15,
    recovered_revenue: 84250.0,
    recovery_rate: 0.75,
    fee_cost: 450.0,
    net_value: 83800.0,
    unnecessary_retries: 0,
    policy_violations: 0,
    escalations: 2,
    average_recovery_time_ms: 45,
  },
  uplift: {
    revenue_gain: 56250.0,
    revenue_uplift_pct: 200.89,
    recovery_rate_diff_pct: 50.0,
    intervention_reduction_pct: 75.0,
  },
  transactions: [
    {
      transaction_id: 'sim_txn_001',
      amount: 4500.0,
      currency: 'INR',
      payment_method: 'UPI',
      failure_code: 'GATEWAY_TIMEOUT',
      risk_score: 0.04,
      baseline: { action: 'BLIND_RETRY', outcome: 'FAILED', time_ms: 1200, blocked: false, escalated: false, unnecessary: true, audit_hash: 'h_base_001' },
      ai: { action: 'SCHEDULE_RETRY', outcome: 'SUCCESS', time_ms: 35, blocked: false, escalated: false, unnecessary: false, audit_hash: 'h_ai_001' },
      ai_won: true,
    },
    {
      transaction_id: 'sim_txn_002',
      amount: 12500.0,
      currency: 'INR',
      payment_method: 'CARD',
      failure_code: 'CARD_DECLINED',
      risk_score: 0.05,
      baseline: { action: 'BLIND_RETRY', outcome: 'FAILED', time_ms: 1400, blocked: false, escalated: false, unnecessary: true, audit_hash: 'h_base_002' },
      ai: { action: 'SWITCH_PAYMENT_METHOD', outcome: 'SUCCESS', time_ms: 42, blocked: false, escalated: false, unnecessary: false, audit_hash: 'h_ai_002' },
      ai_won: true,
    },
    {
      transaction_id: 'sim_txn_003',
      amount: 65000.0,
      currency: 'INR',
      payment_method: 'NETBANKING',
      failure_code: 'HIGH_RISK',
      risk_score: 0.89,
      baseline: { action: 'BLIND_RETRY', outcome: 'SUCCESS', time_ms: 900, blocked: false, escalated: false, unnecessary: false, audit_hash: 'h_base_003' },
      ai: { action: 'STOP', outcome: 'BLOCKED_FRAUD', time_ms: 12, blocked: true, escalated: false, unnecessary: false, audit_hash: 'h_ai_003' },
      ai_won: true,
    },
  ],
};

export const MOCK_CHECKOUT_SESSIONS = [
  {
    session_id: 'chk_sess_001',
    customer_id: 'cust_arun_kumar',
    cart_value: 3499.0,
    current_stage: 'PAYMENT_DROPOFF',
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date().toISOString(),
    checkout_duration: 240,
    device: 'MOBILE_ANDROID',
    payment_method: 'UPI',
    previous_purchases: 4,
    previous_abandonment_count: 1,
    risk_score: 0.04,
    dnd_enabled: false,
    customer_tier: 'GOLD',
    abandonment_detected: true,
    abandonment_reason: 'UPI_INTENT_TIMEOUT',
    recovery_action: 'SEND_WHATSAPP_LINK',
    recovery_probability: 0.82,
    expected_recovery_value: 2869.0,
    policy_outcome: 'PERMITTED',
    policy_rule_id: 'POL-007',
    recovered: true,
  },
  {
    session_id: 'chk_sess_002',
    customer_id: 'cust_priya_sharma',
    cart_value: 8990.0,
    current_stage: 'CARD_INPUT_DROPOFF',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    checkout_duration: 310,
    device: 'DESKTOP_MAC',
    payment_method: 'CARD',
    previous_purchases: 8,
    previous_abandonment_count: 0,
    risk_score: 0.02,
    dnd_enabled: false,
    customer_tier: 'PLATINUM',
    abandonment_detected: true,
    abandonment_reason: '3DS_OTP_ABANDONED',
    recovery_action: 'RETRY_WITH_SEAMLESS_UPI',
    recovery_probability: 0.76,
    expected_recovery_value: 6832.0,
    policy_outcome: 'PERMITTED',
    policy_rule_id: 'POL-004',
    recovered: true,
  },
];
